### ISSUE TITLE
Support for product addons that get displayed in order information

### ISSUE THREAD

**Issue by jvelo** [mayocat/mayocat-shop#136]
Example of such addons declaration : 

```
addons:
  orderInfo:
    name: Order information
    for: product
    fields:
      sku:
        name: SKU
        type: string
        properties:
          checkout.includeInOrder: true
      cardboard:
        name: Cardboard type
        type: string
        properties:
          checkout.includeInOrder: true
```
