### ISSUE TITLE
Support for sizing/cropping for image addons

### ISSUE THREAD

**Issue by jvelo** [mayocat/mayocat-shop#180]
With :
- possibility to reference theme/platform defined standard sizes
- possibility to add new sizes definition just for that addon
- all the defined (referenced or addon-specific) sizes available in the "row" object

Complete definition example: 

```
      my_addon_image:
        name: Name of the image addon
        type: image
        properties:
          image.width: 100
          image.height: 100
          image.referencedSizes: ["caroussel", "mobile_thumbnail"]
          image.otherSizes:
             post:
               width: 624
               height: 354
               name: Specific carrousel for addon
```
