### ISSUE TITLE
Placehold.it URL is incorrect when a only one dimension is specified in image format

### ISSUE THREAD

**Issue by nesk** [mayocat/mayocat-shop#88]
When you specify only one size for a thumbnail in your `theme.yml` file (see the "product" part):

```
images:
  slideshow:
    width: 930
    height: 382
    name: Carrousel
    for: page
  product:
    width: 140
    name: Produit
    for: product
  people:
    width: 295
    height: 177
    name: Photo de profil
    for: page
```

The Handlebars context contains some incorrect placehold.it URLs if there is no image uploaded:

```
"images": {
    "featured": {
        "theme_product_url": "http://placehold.it/140xnull",
        "theme_slideshow_url": "http://placehold.it/930x382",
        "theme_people_url": "http://placehold.it/295x177",
        "url": "http://placehold.it/800x800"
    },
    "all": [{
        "theme_product_url": "http://placehold.it/140xnull",
        "theme_slideshow_url": "http://placehold.it/930x382",
        "theme_people_url": "http://placehold.it/295x177",
        "url": "http://placehold.it/800x800"
    }]
}
```
